# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm ci --ignore-scripts

# Copy app source code
COPY . .

# Build the app
RUN npm run build

# Expose any relevant port if needed (MCP uses stdio so not necessary)

# Start the MCP server
CMD ["node", "dist/index.js"]
